### PR TITLE
Update recipes.py

### PR DESCRIPTION
**Pull request by JoLo90**
### PURPOSE
The calculation of the window coordinates has been modified using the weighted vectors of the X Y Z coordinates so that triangular windows don't extend of the surface anymore. Rectangular windows geometry also looks a bit more realistic. 

### TEST with updated recipes.py

**With the following Geomeppy WWR configuration:**
idf.set_wwr(wwr_map={90: 0.1 ,180: 0.4,270: 0.7,0: 1.0})    

**The corresponding E+ HTML TAB is:**
HTMLresultsWWR

There is a slight discrepancy due to the 0.999 factor but the WWR in the table are equal to the input values.

### CODE REVIEW

**Comment by jamiebull1** [comment]
Looks good, thanks a lot for this. 

Couple of things: 

- Could you write a test to show that the resulting window to wall ratios are as expected for triangular windows (allow a 0.5% tolerance)
- And can you run `black -l 88 geomeppy tests docs setup.py release.py` to lint the code as the CI is failing

**Comment by JoLo90** [comment]
> * And can you run `black -l 88 geomeppy tests` to lint the code as the CI is failing

I don't know yet how to do this but I'll try tomorrow

**Comment by jamiebull1** [comment]
>I don't know yet how to do this but I'll try tomorrow

Great, thanks.

`pip install black` will install [black](https://pypi.org/project/black/)

Then `black -l 88 geomeppy tests` will automatically fix any formatting issues in the `geomeppy` and `tests` directories.

**Comment by JoLo90** [comment]
Thanks Jamie,

when running from the anaconda prompt and pointing to the _GitHub\geomeppy\tests_ folder :

```
(base) C:\Users\Johann>black -l 88 C:\Users\Johann\Documents\GitHub\geomeppy\tests
All done! ? ?? ?
16 files left unchanged.
```

Did I do it the right way ?

**Comment by jamiebull1** [comment]
It looks like you've done the right thing. The snippet I gave you was to run from the root directory of your copy of the geomeppy repo, which contains both the `geomeppy` and `tests` directories. The way you've done it will also work though.

You'll need to commit and push with the reformatted `recipes.py` so the CI will pass, then we're good to go.

Thanks for the test as well. Looking good.

**Comment by JoLo90** [comment]
Thank you, it also worked the way you told me.
Before commiting I opened a new issue concerning the **wwr_map** function which is imo missfunctioning with the case wwr = 0. 
The result is the same with both recipes.py version: the wwr is set to 0.2 instead of 0.

**Pull request closed without merging**
