### PR TITLE
fix: use items() for py2.7 + py3 compatibility

### PR DESCRIPTION
**Pull request by spolloni**
I am running into the python3  'core/perim' issue that #88 fixes, among other things.  #88 has several conflicts and a big diff that I don't fully understand so I am submitting this fix as separate PR.

### CODE REVIEW

**Comment by lymereJ** [comment]
The actual fixes from #88 are in c380aa774687cad7b145be7ec6cefc21778a2208. 

@jamiebull1 - As @spolloni pointed out, it seems that they were not actually merged. Would you like me to create a new PR just like this one for the other proposed changes?

**Comment by jamiebull1** [comment]
@lymereJ If you wouldn't mind, I'll do my best to find time to merge it

**Comment by lymereJ** [comment]
Sounds good, I'll do it this week.

**Comment by lymereJ** [comment]
Addressed in #186.

**Comment by jamiebull1** [comment]
Closing as fixed by @lymereJ and released in v0.11.8

**Pull request closed without merging**
