### PR TITLE
Core/perim approach fixes

### PR DESCRIPTION
**Pull request by lymereJ**
While updating the documentation I noticed that:
- dict.iteritems() is not valid in Python 3.x
- the vertices of the core zone where not returned in counter-clockwise order which was leading to matching problems

This PR fixes these two issues.

### CODE REVIEW

**Comment by lymereJ** [comment]
I'm using Github desktop and as you can see in the screenshot below I only committed changes to `polygons.py` and `idf.py`. I started updating the documentation but didn't commit any changes yet, so I'm not sure why it was included in this commit. Oh well, the content of the file is what I intended to commit later on.

image

**Comment by jamiebull1** [comment]
Sorry, I totally missed this. I'll get to it asap.

**Comment by lymereJ** [comment]
Looks like you did it, didn't you? It shows conflicts but I don't have access to resolve them.

**Comment by jamiebull1** [comment]
Not sure what's going on here. The `Resolve conflicts` button is greyed-out for me too, but I'm pretty sure this is all merged. I'm just working on making a release to fix a couple of pipeline issues that we've had for a while, so the changes should all be on PyPI soon.

**Pull request closed without merging**
